### ISSUE TITLE
Add support for ANSI escape codes to our log viewer

### ISSUE THREAD

**Issue by epeschard** [stanwood/Bitrise_Android#25]
https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by ubuntudroid** [comment]
I improved rendering a bit, but am ignoring the ANSI escape codes for now.

Before:
![before](https://user-images.githubusercontent.com/519867/47026814-961aac80-d166-11e8-9524-672312ab14e7.png)

After:
![after](https://user-images.githubusercontent.com/519867/47026822-9b77f700-d166-11e8-82e9-907ad726ddf9.png)
