### ISSUE TITLE
APK missing from latest tag (1.5)

### ISSUE THREAD

**Issue by IzzySoft** [stanwood/Bitrise_Android#76]
Could you please attach the APK to the latest release, as it was done with the previous one? Thanks in advance!

**Comment by IzzySoft** [comment]
@ubuntudroid @mmoczkowski any chance?

**Comment by mmoczkowski** [comment]
@IzzySoft Sorry about the delay, it's done :)

**Comment by IzzySoft** [comment]
Thanks, went fine! Please keep it up :wink:
